apply plugin: 'com.android.application'

android {
    buildToolsVersion = "35.0.0"

    defaultConfig {
        applicationId 'com.dean.flowtextviewsampleapp.sample'
        minSdkVersion 14
        targetSdkVersion 35
        versionCode 1
        versionName '1.0'
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
    namespace 'uk.co.deanwild.flowtextview.sample'
    compileSdk 35
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation project(':flowtextview')
}
