apply plugin: 'com.android.library'


android {
    buildToolsVersion = "35.0.0"

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35

        versionCode 2100
        versionName "2.1.0 Development Version"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'uk.co.deanwild.flowtextview.flowtextview'
    compileSdk 35
}


